name: ProfessionPlugin
version: '1.0'
main: org.vac.professionplugin.ProfessionManager
api-version: '1.20'

commands:
  setprofesion:
    description: Selecion de Profecion
    usage: /<command> <profesio>

  getprofesion:
    description: obtencion de Profecion
    usage: /<command>

  salirprofesion:
    description: Dejar de trabajar
    usage: /<command>

  test:
    description: comandos para test
    usage: /<command>